### ISSUE TITLE
Errors running setup.py test

### ISSUE THREAD

**Issue by AnthonyLim23** [bonfus/muesr#5]
I am trying to run setup.py test and I am getting the below errors: 

```
======================================================================
FAIL: test_desc_property (muesr.tests.core.test_magmodel.TestMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osboxes/work/Muesr/muesr/muesr/tests/core/test_magmodel.py", line 161, in test_desc_property
    self._mm.desc = 1
AssertionError: TypeError not raised

======================================================================
FAIL: test_desc_property (muesr.tests.core.test_magmodel.TestSMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osboxes/work/Muesr/muesr/muesr/tests/core/test_magmodel.py", line 270, in test_desc_property
    self._smm.desc = 1
AssertionError: TypeError not raised

======================================================================
FAIL: test_mcif3 (muesr.tests.test_muesr.TestMuesr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osboxes/work/Muesr/muesr/muesr/tests/test_muesr.py", line 428, in test_mcif3
    np.testing.assert_array_almost_equal(r2[0].C,np.array([13.2372 , -24.4705 , 9.48213]),decimal=4)
  File "/home/osboxes/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 979, in assert_array_almost_equal
    precision=decimal)
  File "/home/osboxes/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 4 decimals

(mismatch 100.0%)
 x: array([ -8.7551,  16.1849,  -6.2715])
 y: array([ 13.2372, -24.4705,   9.4821])

----------------------------------------------------------------------
Ran 80 tests in 2.987s

FAILED (failures=3, errors=1)

```

I have tried with both python 2 and 3. I have installed all of the packages from http://muesr.readthedocs.io/en/latest/Install.html and running on Ubuntu 16.04. 

I can install the code without a problem, I am just concerned about the tests failing. I was wondering if there were any additional packages that may have been missed from the documentation or if it is the operating system. 

Thanks,
Anthony

**Comment by bonfus** [comment]
Dear Anthony,
thanks for reporting the issue. The first two failures in the test (test_desc_property) should be solved by commit [c2ce01d](https://github.com/bonfus/muesr/commit/c2ce01d5a5a2d0ac23191e2ab9d1bfe38259f8c2).

The test `test_mcif3` originates from the way the contact hyperfine field is described in the code as of today. The test reports the fact that, in the current implementation, reasonable approximations can only be obtained in ferromagnetic configurations (or quasi-ferromagnetic orders, i.e. spirals small canting angles between neighboring atoms). The results in antiferromagnets strongly depend on the parameters that are used in the scalar coupling approximation currently used in the code. I'll hopefully provide more details about this in the documentation soon.
